# Generated by Django 2.2.7 on 2020-04-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=20)),
                ('yourTelephone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('otherName', models.CharField(max_length=40)),
                ('otherTelephone', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
