# Generated by Django 2.2.7 on 2020-04-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
    ]
